// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcvoHVzv70itLH6AyvSJizVH9-FdPGb88',
    appId: '1:156960955122:android:4f9528e59c645baff00e6b',
    messagingSenderId: '156960955122',
    projectId: 'fin-flow-26m8k6',
    storageBucket: 'fin-flow-26m8k6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy3DcEsXXpFqxeBOujaoYZV01s21qM9V8',
    appId: '1:156960955122:ios:db6ccd073b525df1f00e6b',
    messagingSenderId: '156960955122',
    projectId: 'fin-flow-26m8k6',
    storageBucket: 'fin-flow-26m8k6.firebasestorage.app',
    iosBundleId: 'com.example.projectsFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkhyP869fgG5xHAKpy8LQF_3zZ027Cy0A',
    appId: '1:156960955122:web:9d400874c4e7915cf00e6b',
    messagingSenderId: '156960955122',
    projectId: 'fin-flow-26m8k6',
    authDomain: 'fin-flow-26m8k6.firebaseapp.com',
    storageBucket: 'fin-flow-26m8k6.firebasestorage.app',
  );
}
